### ISSUE TITLE
Inkscape-figures watch shutting down

### ISSUE THREAD

**Issue by CemYilmazTech** [gillescastel/inkscape-figures#52]
For those who are curious as to why they have to re-launch inkscape-figures watch every single type after ctrl+f in vimtex or why your pdfs output blanks, please install xclip. It seems to fix the problem for me.

**Comment by CemYilmazTech** [comment]
See the issue above:
```
Traceback (most recent call last):
  File "/home/xein/.local/bin/inkscape-figures", line 4, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xein/.local/lib/python3.12/site-packages/inkscapefigures/main.py", line 114, in watch
    watcher_cmd()
  File "/home/xein/.local/lib/python3.12/site-packages/inkscapefigures/main.py", line 215, in watch_daemon_inotify
    maybe_recompile_figure(path)
  File "/home/xein/.local/lib/python3.12/site-packages/inkscapefigures/main.py", line 174, in maybe_recompile_figure
    pyperclip.copy(latex_template(name, beautify(name)))
  File "/home/xein/.local/lib/python3.12/site-packages/pyperclip/__init__.py", line 622, in lazy_load_stub_copy
    return copy(text)
           ^^^^^^^^^^
  File "/home/xein/.local/lib/python3.12/site-packages/pyperclip/__init__.py", line 295, in __call__
    raise PyperclipException('Pyperclip could not find a copy/paste mechanism for your system. For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error' + additionalInfo)
pyperclip.PyperclipException: Pyperclip could not find a copy/paste mechanism for your system. For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error
On Linux, you can run `sudo apt-get install xclip` or `sudo apt-get install xselect` to install a copy/paste mechanism.
DEBUG:inotify.adapters:Cleaning-up inotify.

```

a quick `sudo apt-get install xclip` fixes the problem
